<?php
/**
 * The header for our theme
 *
 * This is the template that displays all of the <head> section and everything up until <div id="content">
 *
 * @link https://developer.wordpress.org/themes/basics/template-files/#template-partials
 *
 * @package _s
 */

include "functions.php";

?>
<!doctype html>
<html lang="en">
<head>
	<meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="assets/css/style.css" type="text/css" media="all" />

    <script type='text/javascript' src='assets/js/modernizr.touch.js'></script>
    <script type='text/javascript' src='assets/js/plugins/object-fit/ls.object-fit.min.js'></script>
    <script type='text/javascript' src='assets/js/lazysizes.min.js'></script>
</head>

<?php //Scrollspy attributes are only used for the bootstrap test page ?>
<body data-spy="scroll" data-target="#my-navbar" data-offset="100">

<div id="page" class="site">
	<a class="skip-link screen-reader-text" href="#main">Skip to content</a>

        <div class="nav-wrap">
            <div class="container">
                <nav id="site-navigation" class="main-navigation navbar navbar-expand-lg navbar-light" role="navigation">
                    <div class="site-branding navbar-brand">
		                <?php //Do not modify the classes or html for the logo as they will be generated by wordpress ?>
                        <a href="/" class="custom-logo-link" rel="home">
                            <img width="200" height="75" src="https://via.placeholder.com/200x75.png?text=Logo" class="custom-logo" alt="Logo alt text" />
                        </a>
                        <?php //End do not edit ?>
                    </div>
                    <span class="sr-only">Toggle navigation</span>
                    <button class="navbar-toggler brand align-self-end" type="button" data-toggle="collapse" data-target="#navbar-collapse-primary" aria-controls="navbar-collapse-primary" aria-expanded="false" aria-label="Toggle navigation">
                        <i class="fa fa-bars"></i>
                    </button>
                    <div id="navbar-collapse-primary" class="collapse navbar-collapse">
                        <?php //Do not modify the menu item classes as these are generated by wordpress ?>
                        <ul id="primary-menu" class="navbar-nav ml-auto">
                            <li id="menu-item-12"
                                class="menu-item menu-item-type-post_type menu-item-object-page menu-item-home current-menu-item page_item page-item-2 current_page_item nav-item nav-item-12 active">
                                <a title="Home" href="/" class="nav-link">Home</a></li>
                            <li id="menu-item-334"
                                class="menu-item menu-item-type-post_type_archive menu-item-object-ti_service nav-item nav-item-334">
                                <a title="Services" href="/page.php" class="nav-link">Page</a>
                            </li>
                            <li id="menu-item-335"
                                class="menu-item menu-item-type-post_type_archive menu-item-object-ti_project nav-item nav-item-335">
                                <a title="Projects" href="/archive.php" class="nav-link">Blog</a>
                            </li>
                            <li id="menu-item-333"
                                class="menu-item menu-item-type-post_type_archive menu-item-object-ti_company nav-item nav-item-333">
                                <a title="Companies" href="/bootstrap.php"
                                   class="nav-link">Bootstrap</a></li>
                            <li id="menu-item-16"
                                class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children nav-item nav-item-16 dropdown">
                                <a title="Our History" href="#" class="dropdown-toggle nav-link" aria-haspopup="true">Dropdown</a>
                                <ul role="menu" class="dropdown-menu dropdown-animate slideIn">
                                    <li id="menu-item-848"
                                        class="menu-item menu-item-type-custom menu-item-object-custom nav-item nav-item-848">
                                        <a title="Dropdown 1" href="/" class="nav-link">Dropdown 1</a></li>
                                    <li id="menu-item-849"
                                        class="menu-item menu-item-type-custom menu-item-object-custom nav-item nav-item-849">
                                        <a title="Dropdown 2" href="#" class="nav-link">Dropdown 2</a></li>
                                    <li id="menu-item-850"
                                        class="menu-item menu-item-type-custom menu-item-object-custom nav-item nav-item-850">
                                        <a title="A longer dropdown for 3" href="/" class="nav-link">A longer dropdown for 3</a></li>
                                </ul>
                            </li>
                        </ul>
	                    <?php //End do not edit ?>
                    </div>
                </nav>
            </div>
        </div>


	<div id="content" class="site-content">
